### ISSUE TITLE
problems in Collections view

### ISSUE THREAD

**Issue by ndrewr** [shui91/backbone-todo#1]
Was playing with the code.
Didn't like the ref to 'model' in your View for the collection. Changed it to 'collection'.
Then made this change:

```
if ($inputText.val()){
    this.collection.add({ title: $inputText.val()}); 
...
```

**Comment by shermanhui** [comment]
I was able to fix the issue I had in line 53 by changing the code to `this.model.create(toDoItem.toJSON());` which Firebase now accepts happily :+1:

**Comment by ndrewr** [comment]
Noice!
Note it also worked by passing the object hash directly (obj literal) as the argument.
From an optimization standpoint, I'd prroballlly prefer that method just cuz it could save on a todoItem instantiation (since create will make another instance).

**Comment by shermanhui** [comment]
Ah I see what you mean. This was just a practice todo project, I don't think I've carried this inefficiency over to the health-tracker app...but thanks for the input! :100:
